Django/clever/clever/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("news.urls"), name="news")
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Django/clever/news/urls.py
from django.urls import path

from . import views
app_name = 'news'
urlpatterns = [
    path("", views.index, name="index"),
    path("item/<int:pk>", views.detail, name="news_item"),
    path("create/", views.create_news, name="create_update_news"),
    path("update/<int:pk>/", views.update_news, name="update_news")
]

Django/clever/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class News(models.Model):
    title = models.CharField(max_length=200,verbose_name="Название события")
    content = models.TextField(verbose_name="Содержание события")
    date_published = models.DateTimeField(default=timezone.now,verbose_name="Дата публикации")
    image = models.ImageField(upload_to="images/",verbose_name="Изображение")
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Автор", null=True, blank=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("news:news_item", kwargs={"pk": self.pk})
class Comments(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name="Новости")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True, blank=True)
    text = models.TextField(verbose_name="Содержание")
    date_published=models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    def __str__(self):
        return str(self.text)
    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural="Комментарии"

Django/clever/news/forms.py
from django.forms import ModelForm
from .models import News, Comments
from django import forms

class NewsModelForm(ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content', 'image']

    def __init__(self, *args, **kwargs):
        super(NewsModelForm, self).__init__(*args, **kwargs)
        self.fields['title'].help_text = ""
        self.fields['title'].label = ""
        self.fields['title'].widget = forms.Textarea(
            attrs={'placeholder': 'Название новости', "rows": 1, "class": "form-control",}
        )
        self.fields['content'].help_text = ""
        self.fields['content'].label = ""
        self.fields['content'].widget = forms.Textarea(
            attrs={'placeholder': 'Содержание новости', "rows": 13, "class": "form-control", }
        )

class CommentModelForm(ModelForm):
    class Meta:
        model = Comments
        fields = ["text"]
    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        self.fields['text'].help_text = ""
        self.fields['text'].label = ""
        self.fields['text'].widget = forms.Textarea(
            attrs={'placeholder': 'Текст комментария', "rows": 1, "class": "form-control",}
        )

Django/clever/news/views.py
from datetime import datetime

from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from .models import News, Comments
from .forms import NewsModelForm, CommentModelForm

def index(request):
    news = News.objects.all()
    search = request.GET.get("search")
    if search:
        news = news.filter(title__icontains=search)
    paginator= Paginator(news, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    title = "Главная страница"
    return render(request, 'news/news_list.html', {'title': title, 'page_obj': page_obj})

def detail(request, pk):
    newss = News.objects.all()
    news = newss.get(pk=pk)
    title = news.title

    first = newss.first().id
    last = newss.last().id
    count = str(request.GET.get("post"))
    comments = Comments.objects.filter(news=news).order_by("-date_published")
    if count == 'prev':
        if news.id == first:
            return redirect('news:news_item',pk=last )
        prev_news = newss.filter(id__lt=news.id).last()
        return redirect('news:news_item',pk=prev_news.id)
    if count == 'next':
        if news.id == last:
            return redirect('news:news_item', pk=first)
        next_news = newss.filter(id__gt=news.id).first()
        return redirect('news:news_item', pk=next_news.id)
    context = {
        "news": news,
        "title": title,
        "comments": comments
    }
    if request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.news = news
            new_comment.save()
            return redirect("news:news_item", pk=pk)
    else:
        form = CommentModelForm()
    context["form"] = form
    return render(request, 'news/news_item.html', context)

def create_news(request):
    title = "Создание новости"
    action = "Создать"
    if request.method == "POST":
        form = NewsModelForm(request.POST, request.FILES)
        if form.is_valid():
            new_news = form.save(commit=False)
            new_news.author = request.user
            new_news.date_published = datetime.now()
            new_news.save()
            return  redirect("item:index")
    else:
        form = NewsModelForm()
    return render(request, 'news/update_news.html', {"title": title, "form": form, "action": action})

def update_news(request, pk):

    action = "Изменить"
    news = News.objects.get(pk=pk)
    title = f'Редактирование {news.title}'
    if request.method == "POST":
        form = NewsModelForm(request.POST, request.FILES,instance=news)
        if form.is_valid():
            form.save()
            return redirect("news:news_item", pk=pk)
    else:
        form = NewsModelForm(instance=news)
    return render(request, 'news/update_news.html', {"title": title, "form": form, "action": action})

Django/clever/news/templates/news/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock%}
    </title>
    <link rel="stylesheet" href="{% static 'news/css/layout.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'news/img/favicon.ico'%}">

<!--    <link rel="stylesheet" href="../../../static/news/css/layout.css">-->
    {% block static %}
        {% endblock%}
</head>
<body>
    <div class="header">
        <div class="left_side">
            <a class="btn btn-warning" href="{% url 'news:index' %}">Главная страница</a>
            <a class="btn btn-warning">Контанты</a>
            <a class="font-size: 35;text-decoration:none;color:black;">{{title}}</a>
        </div>
        <div class="right_side">
            {% if user.is_authenticated %}
                <a>Здаров, {{user.username}}</a>
                {% if user.is_superuser %}
                    <a class="btn btn-warning" href="{% url 'admin:index' %}"><i class="fa fa-cog"></i></a>
                {% endif %}
                <a class="btn btn-danger ml-2">Выйти</a>
            {% else %}
                <a class="btn btn-primary">Вход</a>
                <a class="btn btn-primary">Регистрация</a>
            {% endif %}
            <a></a>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

Django/clever/news/templates/news/news_item.html
{% extends 'news/layout.html'%}
{% load static %}
{% block title%}News{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static 'news/css/item.css' %}">
{% endblock%}
{% block content %}
    <div style="background: url({{news.image.url}});background-repeat: space;background-position: center;background-size: cover;min-height: 1000px;"
    >
        <div class="list">
            <div class="top">
                <a class="arrow btn btn-light" href="{% url 'news:news_item' pk=news.id %}?post=prev"><i class="fa fa-arrow-left"></i></a>
            <img style="width: 300px; height: auto" src="{{ news.image.url}}"/>
            <div class="content">
                <a class="title">{{news.title}}</a>
                <a class="body">{{news.content|linebreaks}}</a>
            </div>
                <a class="arrow btn btn-right" href="{% url 'news:news_item' pk=news.id %}?post=next"><i class="fa fa-arrow-right"></i></a>
        </div>
            <div class="comments">
                {% if user.is_authenticated%}
                <div>
                    <h3>Ваш комментарий</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit">Отправить</button>
                    </form>
                </div>
                {% else %}
                <h1>Воойдите или зарегестрируйтесь, чтобы оставить комментарий</h1>
                {% endif %}
                {% if comments %}
                    {% for comment in comments %}
                        <div class="comment">
                            <a>{{comment.author}}</a>
                            <a>{{comment.text}}</a>
                            <a>{{comment.date_published}}</a>

                        </div>
                    {% endfor %}
                {% else %}
                    <a>Комментариев пока нет</a>
                {% endif %}
            </div>
        <div>
            <a class="author">{{news.author}}</a>
            <a class="date_published">{{news.date_published}}</a>
        </div>
        </div>


    </div>
{% endblock %}

Django/clever/news/templates/news/news_list.html
{% extends 'news/layout.html'%}
{% load static %}
{% block title%}News{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static 'news/css/news_list.css' %}">
{% endblock%}
{% block content %}
    {% if user.is_superuser%}
    <a class="btn btn-success" href="{% url 'news:create_update_news' %}">Опубликовать новость</a>
    {% endif %}
<form method="get">
    <input type="text" name="search" placeholder="Поиск новости">
    <input type="submit" value="Поиск">
</form>
        {% for new in page_obj %}
            <div class="blog"
                 style="background: url({{new.image.url}});background-repeat: no-repeat;background-position: center;background-size: cover">
                <a class="title" href="{{new.get_absolute_url}}">{{new.title}}</a>
                <div class="content">
                    <a>{{new.author}}</a>
                    <a>{{new.date_published}}</a>
                </div>{% if user.is_superuser%}
            <a class="btn btn-success" href="{% url 'news:update_news' pk=new.id %}"><i class="fa fa-pen"></i></a>
        {% endif %}
            </div>

        {% endfor %}

    </div>
<div>
    <span>
        {% if page_obj.has_previous%}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{page_obj.previous_page_number">previous</a>
        {% endif %}
        <span>
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
        </span>
        {% if page_obj.has_next%}
        <a href="?page={{page_obj.next_page_number}}">next</a>
        <a href="?page={{page_obj.pagination.num_pages">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

Django/clever/news/templates/news/update_news.html
{% extends 'news/layout.html'%}
{% load static %}
{% block title%}News{% endblock %}
{% block static %}
<link rel="stylesheet" href="{% static 'news/css/update_news.css' %}">
{% endblock%}
{% block content %}
    <div>
        <form method="post" enctype="multipart/form-data">
            <div>
                {% csrf_token %}
                {{ form.title }}<br>
                {{ form.content }}<br>
                {{ form.image }}<br>
                <button type="submit" class="btn btn-success">{{action}}</button>

            </div>
        </form>
    </div>
{% endblock %}